version: "3"

services:

  selenium-hub:

    image: selenium/hub:3.141.59

    container_name: selenium-hub

    ports:

      - "4444:4444"

    networks:
        - front-tier
  chrome:
    image: selenium/node-chrome:94.0.4606.54
    container_name: chrome_latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
      - SE_EVENT_BUS_HOST=selenium-hub 
    ports:

      - "5900:5900"
    networks:
        - front-tier
  
  firefox:
    image: selenium/node-firefox:92.0.1
    container_name: "firefox_latest"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
      - SE_EVENT_BUS_HOST=selenium-hub
    ports:
      - "5901:5900"
    networks:
        - front-tier

  real_device:

    image: appium/appium

    depends_on:

      - selenium-hub

    network_mode: "service:selenium-hub"

    privileged: true

    volumes:

      - /dev/bus/usb:/dev/bus/usb

      - ~/.android:/root/.android

      - $PWD/example/sample_apk:/root/tmp

    environment:

      - CONNECT_TO_GRID=true

      - SELENIUM_HOST=selenium-hub

      # Enable it for msite testing

      - BROWSER_NAME=chrome

  samsung_galaxy_web_7.1.1:
    image: budtmo/docker-android-x86-8.1
    privileged: true
    # Increase scale number if needed
    scale: 1
    depends_on:
      - selenium-hub
      - real_device
    ports:
      - "6080:6080"
    networks:
      - front-tier
    volumes:
      - ./video-samsung_7.1.1:/tmp/video
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium-hub
      - MOBILE_WEB_TEST=true
      - AUTO_RECORD=true

  database:
    image: dockersamples/atsea_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    ports:
      - "5432:5432"
    networks:
      - back-tier
    secrets:
      - postgres_password

  appserver:
    image: dockersamples/atsea_app
    container_name: atsea
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

  tests:
    build:
      context: ./src_code
      dockerfile: Dockerfile
    container_name: tests
    tty: true
    networks:
      - front-tier

secrets:
  postgres_password:
    file: ./pg_psw

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay
